version: "3"

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: swotnginx:latest
        ports:
            - 80:80
        depends_on:
            - backend
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        image: swotbackend:latest
        expose:
            - 3000
        command: "npm start"
